version: 19
jobs:
- name: Create docs
  jobExecutor: Main
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !RunContainerStep
    name: phpdoc
    image: phpdoc/phpdoc:3
    args: -d src/ -t docs/
    volumeMounts:
    - sourcePath: .
      targetPath: /data
    - sourcePath: docs/
      targetPath: /data/docs
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishSiteStep
    name: Documentation
    artifacts: docs
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
